### ISSUE TITLE
Math for all versions

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#135]
What would you like to add: 
Math 
How would you want it to be implemented:
Use the file directory called "https://toonigy.github.io/prodigy-classic/" for some files to get math installed.
Any additional context:
Slappygig/Toonigy got math working for 1.37.0.

**Comment by Daboss7173** [comment]
Well, there are a couple problems with this issue.

1: It's not like math would be an upgrade that would make the game better, in fact some people really don't like the math. For that reason, it would be far better for it to be an optional mod or something like that, rather than just being forced into all of the versions.

2: Even if I did add it, I would probably do it myself. I've learned that's the only way it's really gonna be done correctly, and that applies here as well. There are still many problems with that math system, and it's most certainly not perfect.

I'm closing this for now, that doesn't mean I'll never do this as a mod or something, but it's definitely not my top-priority at the moment, and I don't want it clogging up the issue section.
