### ISSUE TITLE
Wizard Watch in your Definitive Edition

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#189]
### What would you like to add?

Wizard Watch in your Definitive Edition

**Comment by Daboss7173** [comment]
I'm sorry, but the thing with wizard watch is... it's used to display game updates as well as updates with friends you have added.

This wouldn't work with Definitive Edition because game updates are already displayed in the mail system, and there is no friend system in Definitive Edition.

With all of this into account; what would Wizard Watch even do? It would just be a heap of nothing served on a platter of air.

Not worth adding.
